yatube/about/urls.py
from django.urls import path

from about import views

from about.apps import AboutConfig


app_name = AboutConfig.name


urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from posts import views
from posts.apps import PostsConfig


app_name = PostsConfig.name


urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name="group_list"),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('create/', views.post_create, name='post_create')
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models


User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название группы')
    slug = models.SlugField(unique=True, verbose_name='Адрес')
    description = models.TextField(verbose_name='Описание')

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title

class Post(models.Model):
    text = models.TextField('Текст поста', help_text='Введите текст поста')
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(
        User, 
        on_delete=models.CASCADE,
        related_name = 'posts', 
        verbose_name='Автор', 
        )
    group = models.ForeignKey(
        Group, 
        blank=True, 
        null=True, 
        on_delete=models.CASCADE, 
        verbose_name='Группа', 
        help_text='Группа, к которой будет относиться пост'
        )
    
    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
    
    def __str__(self):
        return self.text[:15]

yatube/posts/forms.py
from django import forms

from posts.models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')
        labels = {
            'text': 'Текст поста',
            'group': "Выберите группу"
        }
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'введите текст поста'}),
            'group': forms.Select(attrs={'class': 'form-control'}),
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect

from posts.forms import PostForm
from posts.models import Post, Group, User


def index(request):
    template = 'posts/index.html'
    title = "Это главная страница проекта YaTube"
    post_list = Post.objects.all().order_by('-pub_date')
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'title': title,
        'page_obj': page_obj
    }

    return render(request, template, context)

def group_posts(request, slug):
    template = 'posts/group_list.html'
    title = "Последние 10 постов группы"
    group = get_object_or_404(Group, slug=slug)
    post_list = Post.objects.filter(group=group).order_by('-pub_date')
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'title': title,
        'group': group,
        'page_obj': page_obj,
    }

    return render(request, template, context)

def profile(request, username):
    title = f"Профайл пользователя: {username}"
    user_name = get_object_or_404(User, username=username)
    post_list = Post.objects.filter(author=user_name.id).all().order_by('-pub_date')
    post_count = post_list.count()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    if user_name == request.user:
        post_author = request.user
    else:
        post_author = ""
        
    context = {
        'title': title,
        'username': user_name,
        'post_count': post_count,
        'page_obj': page_obj,
        'post_author': post_author
    }

    return render(request, 'posts/profile.html', context)

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post_count = Post.objects.filter(author=post.author.id).count()

    if post.author == request.user:
        post_author = request.user
    else:
        post_author = ""
    
    context = {
        'post': post,
        'post_count': post_count,
        'post_author': post_author
    }

    return render(request, 'posts/post_detail.html', context)

@login_required
def post_create(request):
    title = "Создание нового поста"

    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', post.author)
    else:
        form = PostForm()

    context = {
        'title': title,
        'form': form
    }

    return render(request, 'posts/create_post.html', context)

@login_required
def post_edit(request, post_id):
    title = "Редактировать запись"
    is_edit = get_object_or_404(Post, id=post_id)

    if is_edit.author != request.user:
        return redirect('posts:post_detail', post_id=is_edit.id)
    
    if request.method == 'POST':
        form = PostForm(request.POST, instance=is_edit)
        if form.is_valid():
            is_edit = form.save()
            return redirect('posts:post_detail', post_id=is_edit.id)
    else:
        form = PostForm(instance=is_edit)
    
    context = {
        'title': title,
        'form': form,
        'is_edit': is_edit
    }

    return render(request, 'posts/create_post.html', context)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %} {{ title }}
{% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
            {% if is_edit %}
                Сохранить
            {% else %}
                Добавить    
            {% endif %}
        </button>
    </form>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
  {% block title %}{{ title }} {{ group.title }}
  {% endblock %}
  {% block content %}
    <div class="container py-5">
      <h1>{{ text }}</h1>
      <h1>{{ group.title }} </h1>
        Записи сообщества: <p>{{ group.description }}</p>
      </p>
      <article>
        {% for post in page_obj %}
        <ul>
          <li>
            Автор: {{ post.author }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date }}
          </li>
        </ul>
        <p>
          {{ post.text }}
        </p>
        {% endfor %}
      </article>
    {% include "includes/paginator.html" %}
  {% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
  {% block title %} {{ title }}
  {% endblock %}
  {% block content %}
    <div class="container py-5">
      {% for post in page_obj%}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text }}</p>        
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы "{{ post.group }}"</a>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include "includes/paginator.html" %}
    </div>
  {% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% block title %} {{ post.text|truncatechars:30 }}
{% endblock %}
{% block content %}
    <div class="row">
        <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
            Дата публикации: {{ title.pub_date |date:"D d M Y" }} 
            </li> 
            {% if title.group %}
                <li class="list-group-item">
                    Группа: "{{ title.group.title }}"
                    <a href="{% url 'posts:group_list' post.group.slug %}">
                        все записи группы 
                    </a>                
                </li>
            {% endif %}
            <li class="list-group-item">
            Автор: {{ title.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                Всего постов автора:  <span >{{ post_count }}</span>
            </li>
            <li class="list-group-item">
            <a href="{% url 'posts:profile' post.author %}">
                все посты пользователя
            </a>
            </li>
        </ul>
        </aside>
        <article class="col-12 col-md-9">
        <p>
            {{ post.text }}
        </p>
        {% if post_author %}
            <a href="{% url 'posts:post_edit' post.pk %}">редактировать запись</a>
        {% endif %}
        </article>
    </div> 
{% endblock content %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %} {{ title }}
{% endblock %}
{% block content %}
      <div class="container py-5">        
        <h1>Все посты пользователя {{ username.get_full_name }} </h1>
        <h3>Всего постов: {{ post_count }} </h3>   
        {% for p in page_obj %}
        <article>
          <ul>
            <li>
              Автор: {{ username.get_full_name }}
              <a href="">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ p.pub_date }} 
            </li>
          </ul>
          <p>
          {{ p.text }} 
          </p>          
            <a href="{% url 'posts:post_detail' p.pk %}">подробная информация</a><br>
            {% if post_author %}
                <a href="{% url 'posts:post_edit' p.pk %}">редактировать запись</a>
            {% endif %}

        </article>   
          
            {% if p.group %}
                <a href="{% url 'posts:group_list' p.group.slug %}">все записи группы "{{ p.group }}"</a>
            {% endif %}
                {% if not forloop.last %}<hr>
            {% endif %}
        {% endfor %}  
        {% include "includes/paginator.html" %}
      </div>
{% endblock content %}